theme: jekyll-theme-minimal
title: Research in Cybersecurity - RGU
description: Cybersecurity involves various measures and technologies such as encryption, firewalls, antivirus software, intrusion detection and prevention systems, access controls, vulnerability detection and others to ensure the confidentiality, integrity, and availability of information and information systems. The cybersecurity researchers at RGU research about these aspects.
